In [1]:
import numpy as np

In [2]:
my_arr = np.arange(21)
my_arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20])

In [3]:
my_arr[10]
my_arr[5:15]

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [4]:
my_arr[5:15:5]

array([ 5, 10])

In [5]:
two_dim = np.array([[0,10,20],[5,15,25],[100,200,300]])
two_dim

array([[  0,  10,  20],
       [  5,  15,  25],
       [100, 200, 300]])

In [6]:
two_dim[0]

array([ 0, 10, 20])

In [7]:
two_dim[1][0].item() # item() to metoda konwertująca tablicę NumPy z jednym elementem na wartość Pythona

5

In [8]:
two_dim[1][0] # bez item() zwraca tablicę NumPy

np.int64(5)

In [9]:
two_dim[1:3,:2] # wybiera wiersze od 1 do 2 (3 nie włącznie) i kolumny od 0 do 1 (2 nie włącznie)

array([[  5,  15],
       [100, 200]])

In [10]:
my_array = np.arange(25).reshape(5,5)
my_array

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [11]:
my_array[(0,1),] # wybiera pierwszy i drugi wiersz

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [12]:
my_array[(0,1)] # element w wierszu 0 i kolumnie 1

np.int64(1)

In [13]:
my_array[[0,1],[0,4]] # elementy (0,0) i (1,4)

array([0, 9])

In [14]:
vals = np.array([100,5,0]) # wartości do wybrania
select = np.random.randint(0,3,size=(4,3)) # losowe indeksy do wyboru wartości z vals
select # pokazuje indeksy

array([[1, 1, 2],
       [2, 2, 2],
       [2, 1, 1],
       [2, 1, 0]], dtype=int32)

In [15]:
vals[select] # wybiera wartości z vals na podstawie indeksów w select

array([[  5,   5,   0],
       [  0,   0,   0],
       [  0,   5,   5],
       [  0,   5, 100]])

In [16]:
macierz = np.arange(9).reshape(3,3)
print(macierz)
macierz[-1, -1]  = 999 # zmienia ostatni element na 999
macierz[1:,1:] = 0 # ustawia dolny prawy 2x2 blok na 0
print('\n', macierz)

[[0 1 2]
 [3 4 5]
 [6 7 8]]

 [[0 1 2]
 [3 0 0]
 [6 0 0]]


Ćwiczenie - znajdź indeksy niezerowych elementów z tablicy

In [17]:
arr  = np.array([1,2,0,0,4,0])
np.nonzero(arr) # zwraca indeksy niezerowych elementów

(array([0, 1, 4]),)

In [18]:
arr  = np.array([1,2,0,0,4,0])
np.where(arr != 0) # zwraca indeksy elementów spełniających warunek - metoda bardziej uniwersalna niż nonzero

(array([0, 1, 4]),)

Masking

In [19]:
arr = np.arange(0,50,5) # tworzy tablicę od 0 do 45 z krokiem 5
arr

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45])

In [20]:
arr > 15 # zwraca tablicę boolowską wskazującą, które elementy spełniają warunek

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [21]:
arr[arr > 15] # wybiera elementy większe od 15

array([20, 25, 30, 35, 40, 45])

In [22]:
(arr<10) | (arr>20) # używa operatora bitowego OR do łączenia warunków

array([ True,  True, False, False, False,  True,  True,  True,  True,
        True])

In [23]:
arr[(arr<10) | (arr>20)] # wybiera elementy mniejsze niż 10 lub większe niż 20

array([ 0,  5, 25, 30, 35, 40, 45])

In [27]:
np.where(arr <= 25) # zwraca indeksy elementów mniejszych lub równych 25

(array([0, 1, 2, 3, 4, 5]),)

Ćwiczenie Wyfiltruj z arr tylko te wartości, które są mniejsze od 10 lub większe bądź równe 20, ale jednocześnie różne od liczby 40. (gdzie arr = np.arange(0,50,5)).

In [33]:
arr = np.arange(0,50,5) # tworzy tablicę od 0 do 45 z krokiem 5
arr[(arr < 10) | ((arr >= 20) & (arr != 40))] # dokładnie to co w zadaniu

array([ 0,  5, 20, 25, 30, 35, 45])

Wykorzystując operator XOR, stwórz macierz o kształcie (4,4), której elementy po głównej przekątnej mają wartość logiczną False, a pozostałe wartość True.

In [37]:
np.arange(16).reshape(4,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [46]:
rows = np.arange(4).reshape(4,1) # tworzy kolumnę z wartościami od 0 do 3
cols = np.arange(4) # tworzy wiersz z wartościami od 0 do 3
print(rows, cols)
matrix = (rows ^ cols).astype(bool) # tworzy macierz logiczną na podstawie XOR .astype(bool) - konwersja na typ boolowski
matrix

[[0]
 [1]
 [2]
 [3]] [0 1 2 3]


array([[False,  True,  True,  True],
       [ True, False,  True,  True],
       [ True,  True, False,  True],
       [ True,  True,  True, False]])

In [48]:
arr = np.arange(20).reshape(4,5)
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [49]:
arr[[3,0,1],:3] # wybiera wiersze 3,0,1 i kolumny 0,1,2

array([[15, 16, 17],
       [ 0,  1,  2],
       [ 5,  6,  7]])

In [50]:
arr.sum()

np.int64(190)

In [51]:
arr[arr.sum(axis=1) > 10,2:] # wybiera wiersze, których suma jest większa niż 10, oraz kolumny od 2 do końca

array([[ 7,  8,  9],
       [12, 13, 14],
       [17, 18, 19]])

Zwróć z macierzy arr wiersz o indeksie nr 2, lecz tylko dla tych kolumn, których suma przekracza 30.

In [56]:
arr[2, arr.sum(axis=0) >34] # wybiera trzeci wiersz (index 2) i kolumny, których suma jest większa niż 34

array([12, 13, 14])

Mamy dane dwie tablice: a i b. Stwórz program filtrujący wartości z b, które korespondują z elementami a i są większe od 100 i mniejsze od 110.

In [58]:
a = np.array([97,101,105,111,117,125])
b = np.array(['a','e','i','o','u','y'])

mask = (a > 100) & (a < 110)
result = b[mask]
result

array(['e', 'i'], dtype='<U1')

(a > 100) & (a < 110): NumPy sprawdza te warunki dla każdego elementu tablicy a.

97: Fałsz

101: Prawda (spełnia oba warunki)

105: Prawda (spełnia oba warunki)

111: Fałsz (za duże)

...i tak dalej.
W rezultacie powstaje maska: [False, True, True, False, False, False].

b[maska]: Bierzemy z tablicy b tylko te elementy, które w masce mają wartość True. Odpowiada to literom 'e' oraz 'i'.

In [66]:
np.array([[0,4,1],[2,0,4]])


array([[0, 4, 1],
       [2, 0, 4]])

In [79]:
tablica = np.array([[0,4,1],[2,0,4]])
minima = tablica.min(axis=1)  # minimalne wartości w każdym wierszu
minima_kolumn = tablica.min(axis=0)  # minimalne wartości w każdej kolumnie
maksima = tablica.max(axis=1)  # maksymalne wartości w każdym wierszu
maksima_kolumn = tablica.max(axis=0)  # maksymalne wartości w każdej kolumnie
print("Minima w wierszach:", minima)
print("Minima w kolumnach:", minima_kolumn)
print("Maksima w wierszach:", maksima)
print("Maksima w kolumnach:", maksima_kolumn)

Minima w wierszach: [0 0]
Minima w kolumnach: [0 0 1]
Maksima w wierszach: [4 4]
Maksima w kolumnach: [2 4 4]


Mając talice odwroc znak wszystkich el > 3 i < 8

In [83]:
minus = np.arange(11)
mask = (minus > 3) & (minus < 8)
minus[mask] *=-1
minus

array([ 0,  1,  2,  3, -4, -5, -6, -7,  8,  9, 10])