In [1]:
import numpy as np

In [5]:
my_arr = np.arange(21)
my_arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20])

In [ ]:
my_arr[10]
my_arr[5:15]

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [9]:
my_arr[5:15:5]

array([ 5, 10])

In [10]:
two_dim = np.array([[0,10,20],[5,15,25],[100,200,300]])
two_dim

array([[  0,  10,  20],
       [  5,  15,  25],
       [100, 200, 300]])

In [11]:
two_dim[0]

array([ 0, 10, 20])

In [ ]:
two_dim[1][0].item() # item() to metoda konwertująca tablicę NumPy z jednym elementem na wartość Pythona

5

In [18]:
two_dim[1][0] # bez item() zwraca tablicę NumPy

np.int64(5)

In [39]:
two_dim[1:3,:2] # wybiera wiersze od 1 do 2 (3 nie włącznie) i kolumny od 0 do 1 (2 nie włącznie)

array([[  5,  15],
       [100, 200]])

In [46]:
my_array = np.arange(25).reshape(5,5)
my_array

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [47]:
my_array[(0,1),] # wybiera pierwszy i drugi wiersz

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [48]:
my_array[(0,1)] # element w wierszu 0 i kolumnie 1

np.int64(1)

In [49]:
my_array[[0,1],[0,4]] # elementy (0,0) i (1,4)

array([0, 9])

In [ ]:
vals = np.array([100,5,0]) # wartości do wybrania
select = np.random.randint(0,3,size=(4,3)) # losowe indeksy do wyboru wartości z vals
select # pokazuje indeksy

array([[2, 0, 0],
       [2, 1, 1],
       [0, 0, 0],
       [1, 0, 2]], dtype=int32)

In [51]:
vals[select] # wybiera wartości z vals na podstawie indeksów w select

array([[  0, 100, 100],
       [  0,   5,   5],
       [100, 100, 100],
       [  5, 100,   0]])

In [52]:
macierz = np.arange(9).reshape(3,3)
print(macierz)
macierz[-1, -1]  = 999 # zmienia ostatni element na 999
macierz[1:,1:] = 0 # ustawia dolny prawy 2x2 blok na 0
print('\n', macierz)

[[0 1 2]
 [3 4 5]
 [6 7 8]]

 [[0 1 2]
 [3 0 0]
 [6 0 0]]


Ćwiczenie - znajdź indeksy niezerowych elementów z tablicy

In [53]:
arr  = np.array([1,2,0,0,4,0])
np.nonzero(arr) # zwraca indeksy niezerowych elementów

(array([0, 1, 4]),)

In [54]:
arr  = np.array([1,2,0,0,4,0])
np.where(arr != 0) # zwraca indeksy elementów spełniających warunek - metoda bardziej uniwersalna niż nonzero

(array([0, 1, 4]),)

Masking

In [ ]:
arr = np.arange(0,50,5) # tworzy tablicę od 0 do 45 z krokiem 5
arr

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45])

In [ ]:
arr > 15 # zwraca tablicę boolowską wskazującą, które elementy spełniają warunek

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [57]:
arr[arr > 15] # wybiera elementy większe od 15

array([20, 25, 30, 35, 40, 45])